title: Notes to Self
name: "So I don't forget"
email: denniswoodruff@gmail.com
description: "My blog is a collection of notes to myself. Mainly things I would otherwise forget very quickly. Now all I have to do is remember where my blog is."
baseurl: ""
url: "http://notes-to-self.denniswoodruff.org.uk"
twitter_username: wsinned
github_username:  wsinned

# Build settings
markdown: kramdown
permalink: pretty
highlight: pygments
